FROM gcr.io/google-appengine/debian9

COPY usr/bin/file usr/bin/file
COPY usr/bin/file usr/bin/
COPY usr/bin/dir /usr/bin/ # Copy over an entire directory
COPY dir/*.go dir/
COPY dir/*go hello.go # Where there is only one go file, so this should work
COPY --from=0 something something