FROM gcr.io/distroless/base:latest AS stage1
COPY context/bar/ba* /dir/

FROM gcr.io/google-appengine/debian9:latest
RUN echo "hello" > /hello
COPY --from=0 /dir/bat /tmp/bat
COPY --from=stage1 /dir/baz /tmp/baz
