FROM gcr.io/google-appengine/debian9:latest
ADD context/foo /foodir/
ADD context/bar/b* bar/
ADD . /allfiles/

ENV contextenv ./context
ADD $contextenv/* /tmp/${contextenv}/

ADD context/tar_archives/*compressed /tars/
