steps:
  # First, install make
  - name: "gcr.io/google-appengine/debian9"
    args: ["sh", "-c", "cp -r . /kaniko/ && mkdir -p /workspace/go/src/github.com/GoogleCloudPlatform/ && cp -r /kaniko/ /workspace/go/src/github.com/GoogleCloudPlatform/"]
  # Then, build the binary
  - name: "golang:1.10"
    args: ["sh", "-c", "make"]
    dir: go/src/github.com/GoogleCloudPlatform/kaniko
    env: ["GOPATH=/workspace/go/"]
  # Then, build kaniko with kaniko
  - name: "gcr.io/priya-wadhwa/executor:latest"
    args: ["--dockerfile=/workspace/deploy/Dockerfile",
           "--context=/workspace/go/src/github.com/GoogleCloudPlatform/kaniko/",
           "--destination=gcr.io/priya-wadhwa/executor:${COMMIT_SHA}"]
